import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import Header from "@/components/global/Header";
import { getCachedArticleCategories, getCachedQuickLinks } from "@/services/CachedServices";
import QuickLinks from "@/components/global/QuickLinks";
import Footer from "@/components/global/Footer";
import JsonLd from "@/components/utils/jsonLd";
import ComscoreTracker from "@/components/global/ComscoreTracker";

const validLocales = ['en', 'hi'];

// Load font variable only once and remove unneeded comment
const inter = Inter({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400",
    "500", "600", "700", "800", "900"
  ],
  display: "swap",
  variable: "--font-inter",
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ORGANIZATION_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Jagran Reviews",
  url: "https://www.jagranreviews.com/",
  logo: {
    "@type": "ImageObject",
    url: process.env.NEXT_PUBLIC_BASE_SITE_SCHEMA_LOGO,
    width: 600,
    height: 60,
  },
  sameAs: [
    "https://www.facebook.com/jagranreviews",
    "https://www.instagram.com/jagranreviews",
    "https://x.com/jagranreviews",
    "https://www.youtube.com/@jagranreviews",
  ],
  address: {
    "@type": "PostalAddress",
    streetAddress: "20th Floor, World Trade Tower",
    addressLocality: "Noida Sector 16",
    addressRegion: "Uttar Pradesh",
    postalCode: "201301",
    addressCountry: {
      "@type": "Country",
      name: "IN",
    },
  },
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+91-120-4694000",
    contactType: "Customer Service",
    areaServed: "IN",
    availableLanguage: "English",
    hoursAvailable: {
      "@type": "OpeningHoursSpecification",
      opens: "09:00",
      closes: "18:00",
    },
  },
};

export default async function LocaleLayout({ children, params }) {
  const { lang } = await params;
  let local;
  let localUrl;
  if (lang === 'en') {
    local = 'en_US'
    localUrl = `/${process.env.NEXT_PUBLIC_MODE_BASE_PATH}`
  } else if (lang === 'hi') {
    local = 'hi_IN'
    localUrl = `/${process.env.NEXT_PUBLIC_MODE_BASE_PATH}/hindi`
  }
  // Fetch initial data in parallel, only await after all have been triggered
  const [articleCategoriesResult, quickLinksResult] = await Promise.allSettled([
    getCachedArticleCategories({local}),
    getCachedQuickLinks({local}),
  ]);
  const articleCategoriesData = articleCategoriesResult.status === "fulfilled"
    ? articleCategoriesResult.value
    : undefined;
  const quickLinksData = quickLinksResult.status === "fulfilled"
    ? quickLinksResult.value
    : undefined;
  return (
    <html lang={lang}>
      <head>
        <link rel="dns-prefetch" href="https://images.herzindagi.info" />
        <link rel="preconnect" href="https://images.herzindagi.info" crossOrigin="anonymous" />
        {/* <link rel="preconnect" href="https://www.googletagmanager.com" /> */}
        {/* <link rel="preconnect" href="https://www.google-analytics.com" />
        <link rel="preconnect" href="https://sb.scorecardresearch.com" /> */}
      </head>
      <body className={`${inter.variable} antialiased`}>
        <JsonLd id="jsonld-organization" data={ORGANIZATION_SCHEMA} />
        <GoogleTagManager gtmId="GTM-W5NRHHKF" />
        <Header header={articleCategoriesData} localUrl={localUrl} local={local} />
        {children}
        <QuickLinks QuickLinkData={quickLinksData} />
        <Footer />
        <ComscoreTracker />
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return validLocales.map((lang) => ({ lang }));
}
